<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Close</name>
   <tag></tag>
   <elementGuidId>cb678833-d0c3-463e-9ee4-180c069d0041</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dismiss-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dismiss-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Close ad&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>17e6533b-b735-4d39-bcf3-0d87de2a614b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ns-mnbet-e-5 close-button</value>
      <webElementGuid>4d0d4498-6345-4c6a-88fe-beb24b92897e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dismiss-button</value>
      <webElementGuid>13da3a3f-b4fe-4b4d-9719-4aa3f33c4fda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-overflow-forbidden</name>
      <type>Main</type>
      <value>xy</value>
      <webElementGuid>b3f27a02-ffef-4ee3-926c-9612d91b0eab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Close ad</value>
      <webElementGuid>4017f43b-b1fb-45a8-be63-7966ec4846ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2433764c-5d8f-4e49-9111-43d2cf7b0a34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ac646050-4d7b-4fd5-870a-108ba18259a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>d915511f-b499-4ad9-8a0f-7adbe96f5c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dismiss-button&quot;)</value>
      <webElementGuid>1c5563b5-2508-4b9a-8660-bf0c216d1d4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Automation Exercise - All Products/iframe_Ad_ad_iframe</value>
      <webElementGuid>6ba717d4-4073-4990-94d7-a818b42cce1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='dismiss-button']</value>
      <webElementGuid>8259b4e5-f41e-44d1-862d-a77e59b29e88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='image-square']/div/div/div</value>
      <webElementGuid>ef855d2e-9825-4e7f-8710-6a04d34e5e5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open'])[1]/preceding::div[3]</value>
      <webElementGuid>33deecae-09e3-463f-8838-5cd6df9fefbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div</value>
      <webElementGuid>d40ae9d0-ffdf-45ba-92a4-e8ee54b4304c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'dismiss-button' and (text() = 'Close' or . = 'Close')]</value>
      <webElementGuid>e04192ea-c1a7-4ec0-a087-9613c5bebf01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
